### ISSUE TITLE
Relative compiled path goes too many directories back

### ISSUE THREAD

**Issue by freddyheppell** [Snapstromegon/eleventy-plugin-rollup#8]
When the plugin generates the path to the compiled JS file, it inserts one too many `../` in the path (see [this page](https://twotwelve.uk/blog/rock-paper-scissors/) for a live example).

For the path `/blog/rock-paper-scissors/` (i.e. the file `/blog/rock-paper-scissors/index.html` it generates the script tag

```html
<script src="../../../assets/js/blog-278a73.js" type="module"></script>
```

but it should be

```html
<script src="../../assets/js/blog-278a73.js" type="module"></script>
```

Browsers seem to ignore the extra one and load the file anyway. This still happens if I use a relative path and pass in `true` as a second argument to the shortcode.

I believe this issue is caused by passing in the output file to `path.relative()`, not its directory.

```js
console.log(path.relative('dist/blog/rock-paper-scissors/index.html', 'dist/assets/js/blog-278a73.js'));
// Returns ../../../assets/js/blog-278a73.js

console.log(path.relative('dist/blog/rock-paper-scissors', 'dist/assets/js/blog-278a73.js'));
// Returns ../../assets/js/blog-571c47.js
```

Modifying the call to `path.relative()` to use `path.dirname(eleventyInstance.page.outputPath)` instead of the raw `outputPath` fixes the issue. I'm happy to submit a PR with this change if this doesn't cause any other problems.

Plugin version: 1.2.0
Node version: 18.8.0
Eleventy version: 1.0.1

**Comment by Snapstromegon** [comment]
Hi,
thanks for opening the issue, feel free to open a PR and I will take a look at it.
